package cz.heller.core.categorize

/**
 * Obecná slova (CZ / SK / PL / DE / EN), která popisují **druh** provozovny nebo platby a
 * zobecňují na obchodníky, které nikdo nezná: „PIZZERIE U KOCOURA" → restaurace, „LEKARNA
 * NA POLIKLINICE" → zdravotní péče. Nejnižší priorita — značky i ruční pravidla vyhrávají.
 * Klíče: normalizované tokeny, `*` = prefix tokenu (viz [Lexicon]).
 */
object GenericLexicon {

    val expense: List<Pair<String, String>> = listOf(
        // --- Potraviny ---
        "potravin*" to "food_groceries",
        "supermarket*" to "food_groceries",
        "hypermarket*" to "food_groceries",
        "supermarkt" to "food_groceries",
        "minimarket*" to "food_groceries",
        "samoobsluh*" to "food_groceries",
        "vecerk*" to "food_groceries",
        "smisene zbozi" to "food_groceries",
        "smisenka" to "food_groceries",
        "ovoce" to "food_groceries",
        "zelenin*" to "food_groceries",
        "reznictv*" to "food_groceries",
        "uzenin*" to "food_groceries",
        "maso" to "food_groceries",
        "mlekarn*" to "food_groceries",
        "lahudk*" to "food_groceries",
        "delikates*" to "food_groceries",
        "napoj*" to "food_groceries",
        "vinotek*" to "food_groceries",
        "alkohol*" to "food_groceries",
        "trznice" to "food_groceries",
        "farmarsk*" to "food_groceries",
        "spozywcz*" to "food_groceries",
        "warzyw*" to "food_groceries",
        "owoce" to "food_groceries",
        "miesn*" to "food_groceries",
        "lebensmittel" to "food_groceries",
        "grocer*" to "food_groceries",
        "market" to "food_groceries",
        "sklep" to "food_groceries",
        // --- Restaurace, fast-food ---
        "restaur*" to "food_dining",
        "*pizza" to "food_dining",
        "*burger" to "food_dining",
        "*bistro" to "food_dining",
        "*grill" to "food_dining",
        "*kebab" to "food_dining",
        "*sushi" to "food_dining",
        "*restaurant" to "food_dining",
        "*restaurace" to "food_dining",
        "foodtruck" to "food_dining",
        "food truck" to "food_dining",
        "*truck" to "food_dining",
        "salaterie" to "food_dining",
        "freshbar" to "food_dining",
        "fresh bar" to "food_dining",
        "vending*" to "food_dining",
        "automat*" to "food_dining",
        "*automat" to "food_dining",
        "asian" to "food_dining",
        "pierog*" to "food_dining",
        "restoran*" to "food_dining",
        "ristorante" to "food_dining",
        "trattoria" to "food_dining",
        "tratoria" to "food_dining",
        "osteria" to "food_dining",
        "taverna" to "food_dining",
        "konoba" to "food_dining",
        "gostilna" to "food_dining",
        "brasserie" to "food_dining",
        "pizz*" to "food_dining",
        "kebab*" to "food_dining",
        "burger*" to "food_dining",
        "bistro*" to "food_dining",
        "hostin*" to "food_dining",
        "jidelna" to "food_dining",
        "jidelni*" to "food_dining",
        "gastro*" to "food_dining",
        "grill*" to "food_dining",
        "gril" to "food_dining",
        "bufet*" to "food_dining",
        "bageteri*" to "food_dining",
        "sushi" to "food_dining",
        "ramen" to "food_dining",
        "wok" to "food_dining",
        "asia" to "food_dining",
        "vietnam*" to "food_dining",
        "thai" to "food_dining",
        "indian" to "food_dining",
        "steak*" to "food_dining",
        "fast food" to "food_dining",
        "fastfood" to "food_dining",
        "food" to "food_dining",
        "kuchyn*" to "food_dining",
        "kuchni*" to "food_dining",
        "jadlo*" to "food_dining",
        "obiad*" to "food_dining",
        "karczm*" to "food_dining",
        "zajazd" to "food_dining",
        "gospoda" to "food_dining",
        "imbiss" to "food_dining",
        "gasthaus" to "food_dining",
        "gasthof" to "food_dining",
        "wirtshaus" to "food_dining",
        "kantyn*" to "food_dining",
        "kantin*" to "food_dining",
        "menza" to "food_dining",
        "catering" to "food_dining",
        "rozvoz" to "food_dining",
        "snack*" to "food_dining",
        "kolonial" to "food_groceries",
        // --- Bar, kavárna ---
        "cafe*" to "food_dining",
        "*cafe" to "food_dining",
        "*kafe" to "food_dining",
        "*kaffee" to "food_dining",
        "*coffee" to "food_dining",
        "caffe*" to "food_dining",
        "kavarn*" to "food_dining",
        "kawiarn*" to "food_dining",
        "coffee" to "food_dining",
        "kafe*" to "food_dining",
        "kafic*" to "food_dining",
        "espresso" to "food_dining",
        "bar" to "food_dining",
        "pub" to "food_dining",
        "hospoda" to "food_dining",
        "hospody" to "food_dining",
        "hospudk*" to "food_dining",
        "pivnic*" to "food_dining",
        "pivovar*" to "food_dining",
        "vinarn*" to "food_dining",
        "winiarn*" to "food_dining",
        "piwnic*" to "food_dining",
        "browar*" to "food_dining",
        "brauhaus" to "food_dining",
        "cukrarn*" to "food_dining",
        "cukiern*" to "food_dining",
        "pekar*" to "food_dining",
        "piekarn*" to "food_dining",
        "backerei" to "food_dining",
        "backer*" to "food_dining",
        "konditorei" to "food_dining",
        "bakery" to "food_dining",
        "*baker" to "food_dining",
        "patisser*" to "food_dining",
        "zmrzlin*" to "food_dining",
        "lody" to "food_dining",
        "lodziarn*" to "food_dining",
        "gelat*" to "food_dining",
        "eiscafe" to "food_dining",
        "cocktail*" to "food_dining",
        "koktejl*" to "food_dining",
        "lounge" to "food_dining",
        "cajovn*" to "food_dining",
        "herbaciarn*" to "food_dining",
        "donut*" to "food_dining",
        "kolac*" to "food_dining",
        "palacink*" to "food_dining",
        "wafl*" to "food_dining",
        "gofr*" to "food_dining",
        "tobacco" to "food_dining",
        "tabak*" to "food_dining",
        "trafik*" to "food_dining",
        "croissant" to "food_dining",
        // --- Palivo ---
        "benzin*" to "transport_fuel",
        "cerpaci*" to "transport_fuel",
        "tankstelle" to "transport_fuel",
        "tankstation" to "transport_fuel",
        "paliv*" to "transport_fuel",
        "stacja paliw" to "transport_fuel",
        "stacja" to "transport_fuel",
        "petrol*" to "transport_fuel",
        "gas station" to "transport_fuel",
        "fuel" to "transport_fuel",
        "lpg" to "transport_fuel",
        "cng" to "transport_fuel",
        "nafta" to "transport_fuel",
        "nabijeci stanice" to "transport_fuel",
        "dobijeci stanice" to "transport_fuel",
        "ladestation" to "transport_fuel",
        "charging" to "transport_fuel",
        // --- Parkování ---
        "parkov*" to "transport_car_other",
        "parking*" to "transport_car_other",
        "parkomat*" to "transport_car_other",
        "parkplatz" to "transport_car_other",
        "parkhaus" to "transport_car_other",
        "garaz*" to "transport_car_other",
        "garage" to "transport_car_other",
        // --- Vozidlo: údržba ---
        "autoserv*" to "transport_car_other",
        "servis" to "transport_car_other",
        "werkstatt" to "transport_car_other",
        "pneu*" to "transport_car_other",
        "opony" to "transport_car_other",
        "reifen*" to "transport_car_other",
        "myci*" to "transport_car_other",
        "mycka" to "transport_car_other",
        "myjni*" to "transport_car_other",
        "autowasch*" to "transport_car_other",
        "waschanl*" to "transport_car_other",
        "car wash" to "transport_car_other",
        "carwash" to "transport_car_other",
        "autodil*" to "transport_car_other",
        "czesci" to "transport_car_other",
        "autoteile" to "transport_car_other",
        "stk" to "transport_car_other",
        "emise" to "transport_car_other",
        "autoskl*" to "transport_car_other",
        "autocentrum" to "transport_car_other",
        "automoto" to "transport_car_other",
        "auto moto" to "transport_car_other",
        "dalnicni" to "transport_car_other",
        "mytne" to "transport_car_other",
        "myto" to "transport_car_other",
        "toll" to "transport_car_other",
        "maut" to "transport_car_other",
        // --- Vozidlo: půjčovna, leasing ---
        "pujcovna aut" to "transport_car_other",
        "autopujcovna" to "transport_car_other",
        "rent a car" to "transport_car_other",
        "car rental" to "transport_car_other",
        "wypozyczalnia" to "transport_car_other",
        "autovermietung" to "transport_car_other",
        "carsharing" to "transport_car_other",
        "car sharing" to "transport_car_other",
        "leasing*" to "transport_car_other",
        "lizing*" to "transport_car_other",
        // --- Veřejná doprava ---
        "mhd" to "transport_public",
        "dopravni podnik" to "transport_public",
        "jizden*" to "transport_public",
        "jizdne" to "transport_public",
        "bilet*" to "transport_public",
        "komunikacja miejska" to "transport_public",
        "verkehrsbetrieb*" to "transport_public",
        "fahrkart*" to "transport_public",
        "tramvaj*" to "transport_public",
        "autobus*" to "transport_public",
        "metro" to "transport_public",
        "prepravn*" to "transport_public",
        "koleje*" to "transport_public",
        // --- Dálková doprava ---
        "vlak*" to "transport_public",
        "zeleznic*" to "transport_public",
        "railway*" to "transport_public",
        "bahn" to "transport_public",
        "pkp" to "transport_public",
        "intercity" to "transport_public",
        "letenk*" to "transport_public",
        "letiste" to "transport_public",
        "airport" to "transport_public",
        "airline*" to "transport_public",
        "airways" to "transport_public",
        "trajekt*" to "transport_public",
        "ferry" to "transport_public",
        // --- Taxi ---
        "taxi*" to "transport_taxi",
        "cab" to "transport_taxi",
        // --- Zdravotní péče, lékárna ---
        "lekarn*" to "health_care",
        "apotek*" to "health_care",
        "apothek*" to "health_care",
        "aptek*" to "health_care",
        "pharmac*" to "health_care",
        "farmaci*" to "health_care",
        "mudr" to "health_care",
        "lekar*" to "health_care",
        "doktor*" to "health_care",
        "ordinac*" to "health_care",
        "poliklinik*" to "health_care",
        "klinik*" to "health_care",
        "clinic*" to "health_care",
        "nemocnic*" to "health_care",
        "szpital*" to "health_care",
        "hospital*" to "health_care",
        "krankenhaus" to "health_care",
        "zubn*" to "health_care",
        "stomatolog*" to "health_care",
        "dentist*" to "health_care",
        "dental*" to "health_care",
        "zahnarzt" to "health_care",
        "optik*" to "health_care",
        "optic*" to "health_care",
        "ocni" to "health_care",
        "okulist*" to "health_care",
        "laborator*" to "health_care",
        "fyzio*" to "health_care",
        "rehabilit*" to "health_care",
        "psycholog*" to "health_care",
        "psychoterap*" to "health_care",
        "terapi*" to "health_care",
        "medicin*" to "health_care",
        "medic*" to "health_care",
        "zdravotni*" to "health_care",
        "gynekolog*" to "health_care",
        "ortoped*" to "health_care",
        "dermatolog*" to "health_care",
        // --- Wellness, krása ---
        "kadern*" to "health_sport",
        "holic*" to "health_sport",
        "barber*" to "health_sport",
        "fryzjer*" to "health_sport",
        "friseur*" to "health_sport",
        "salon*" to "health_sport",
        "manikur*" to "health_sport",
        "pedikur*" to "health_sport",
        "nehtov*" to "health_sport",
        "nail*" to "health_sport",
        "masaz*" to "health_sport",
        "massage*" to "health_sport",
        "spa" to "health_sport",
        "wellness" to "health_sport",
        "sauna" to "health_sport",
        "lazne" to "health_sport",
        "koupalist*" to "health_sport",
        "solarium" to "health_sport",
        "tetov*" to "health_sport",
        "tattoo" to "health_sport",
        "beauty" to "health_sport",
        // --- Sport, fitness ---
        "fitness*" to "health_sport",
        "fitko" to "health_sport",
        "posilovn*" to "health_sport",
        "silownia" to "health_sport",
        "gym" to "health_sport",
        "telocvic*" to "health_sport",
        "bazen*" to "health_sport",
        "plavec*" to "health_sport",
        "plovarn*" to "health_sport",
        "aquapark*" to "health_sport",
        "aquaparc*" to "health_sport",
        "aquacentrum" to "health_sport",
        "sport*" to "health_sport",
        "*sport" to "health_sport",
        "squash" to "health_sport",
        "badminton" to "health_sport",
        "tenis*" to "health_sport",
        "golf*" to "health_sport",
        "lyz*" to "health_sport",
        "ski" to "health_sport",
        "skiareal" to "health_sport",
        "skipas*" to "health_sport",
        "skicentrum" to "health_sport",
        "lanov*" to "health_sport",
        "vlek*" to "health_sport",
        "cyklo*" to "health_sport",
        "bike*" to "health_sport",
        "marathon" to "health_sport",
        "maraton" to "health_sport",
        "yoga" to "health_sport",
        "joga" to "health_sport",
        "pilates" to "health_sport",
        "crossfit" to "health_sport",
        "boulder*" to "health_sport",
        "lezec*" to "health_sport",
        "horolez*" to "health_sport",
        "climbing" to "health_sport",
        "hokej*" to "health_sport",
        "fotbal*" to "health_sport",
        "futsal" to "health_sport",
        "hriste" to "health_sport",
        "sokol" to "health_sport",
        // --- Kultura, vstupenky ---
        "kino" to "leisure_culture",
        "cinema*" to "leisure_culture",
        "multikino" to "leisure_culture",
        "divadl*" to "leisure_culture",
        "teatr*" to "leisure_culture",
        "theater" to "leisure_culture",
        "theatre" to "leisure_culture",
        "koncert*" to "leisure_culture",
        "concert*" to "leisure_culture",
        "vstupenk*" to "leisure_culture",
        "vstupne" to "leisure_culture",
        "ticket*" to "leisure_culture",
        "muzeum" to "leisure_culture",
        "museum" to "leisure_culture",
        "galeri*" to "leisure_culture",
        "vystav*" to "leisure_culture",
        "festival*" to "leisure_culture",
        "zoo" to "leisure_culture",
        "zoologick*" to "leisure_culture",
        "hrad" to "leisure_culture",
        "zamek" to "leisure_culture",
        "comedy" to "leisure_culture",
        "opera" to "leisure_culture",
        "jazz club" to "leisure_culture",
        "jazz" to "leisure_culture",
        "filharmon*" to "leisure_culture",
        "planetarium" to "leisure_culture",
        "bowling" to "leisure_culture",
        // --- Dovolená, ubytování ---
        "hotel*" to "leisure_holidays",
        "*hotel" to "leisure_holidays",
        "hostel*" to "leisure_holidays",
        "motel*" to "leisure_holidays",
        "*camp" to "leisure_holidays",
        "schronisko" to "leisure_holidays",
        "penzion*" to "leisure_holidays",
        "pension*" to "leisure_holidays",
        "apartm*" to "leisure_holidays",
        "apartam*" to "leisure_holidays",
        "ubytov*" to "leisure_holidays",
        "nocleh*" to "leisure_holidays",
        "nocleg*" to "leisure_holidays",
        "chata" to "leisure_holidays",
        "chalupa" to "leisure_holidays",
        "camp*" to "leisure_holidays",
        "kemp*" to "leisure_holidays",
        "resort" to "leisure_holidays",
        "zajezd*" to "leisure_holidays",
        "cestovni kancelar" to "leisure_holidays",
        "cestovni agentura" to "leisure_holidays",
        "biuro podrozy" to "leisure_holidays",
        "reiseburo" to "leisure_holidays",
        "tour*" to "leisure_holidays",
        "travel*" to "leisure_holidays",
        "dovolen*" to "leisure_holidays",
        "lazensk*" to "leisure_holidays",
        // --- Vzdělávání ---
        "skola" to "leisure_education",
        "skol*" to "leisure_education",
        "szkol*" to "leisure_education",
        "schule" to "leisure_education",
        "kurz*" to "leisure_education",
        "kurs*" to "leisure_education",
        "course*" to "leisure_education",
        "lekce" to "leisure_education",
        "lektor*" to "leisure_education",
        "vyuka" to "leisure_education",
        "jazykov*" to "leisure_education",
        "autoskol*" to "leisure_education",
        "univerzit*" to "leisure_education",
        "universit*" to "leisure_education",
        "vysoka skola" to "leisure_education",
        "fakult*" to "leisure_education",
        "skolne" to "leisure_education",
        "doucov*" to "leisure_education",
        "vzdelav*" to "leisure_education",
        "seminar*" to "leisure_education",
        "workshop*" to "leisure_education",
        // --- Knihy, audio, předplatné ---
        "knih*" to "leisure_culture",
        "ksiegar*" to "leisure_culture",
        "ksiazk*" to "leisure_culture",
        "buchhandl*" to "leisure_culture",
        "book*" to "leisure_culture",
        "audiokni*" to "leisure_culture",
        "predplatn*" to "leisure_culture",
        "subscription" to "leisure_culture",
        "prenumerat*" to "leisure_culture",
        "casopis*" to "leisure_culture",
        "noviny" to "leisure_culture",
        "magazin*" to "leisure_culture",
        "knihovn*" to "leisure_culture",
        // --- Televize, streaming ---
        "streaming" to "comm_apps",
        "televiz*" to "comm_apps",
        "kabelov*" to "comm_apps",
        "satelit*" to "comm_apps",
        // --- Charita, dary ---
        "charit*" to "charity",
        "nadac*" to "charity",
        "nadace" to "charity",
        "sbirk*" to "charity",
        "fundacj*" to "charity",
        "spende*" to "charity",
        "donation*" to "charity",
        "dobrocin*" to "charity",
        "dar" to "charity",
        "dary" to "charity",
        "svatebni dar" to "charity",
        "prispevek na" to "charity",
        // --- Koníčky ---
        "hobby" to "leisure_culture",
        "modelar*" to "leisure_culture",
        "rybar*" to "leisure_culture",
        "wedkar*" to "leisure_culture",
        "mysliv*" to "leisure_culture",
        "hudebni nastroj*" to "leisure_culture",
        "kytar*" to "leisure_culture",
        "foto*" to "leisure_culture",
        "umeleck*" to "leisure_culture",
        "vytvarn*" to "leisure_culture",
        "kreativ*" to "leisure_culture",
        "sberatel*" to "leisure_culture",
        "deskov*" to "leisure_culture",
        // --- Životní události ---
        "svatb*" to "others",
        "svateb*" to "others",
        "wedding" to "others",
        "pohreb*" to "others",
        "pohrebni" to "others",
        "funeral" to "others",
        "bestattung*" to "others",
        "oslav*" to "others",
        "narozenin*" to "others",
        // --- Oděvy a obuv ---
        "odev*" to "shopping_clothes",
        "oblec*" to "shopping_clothes",
        "obuv*" to "shopping_clothes",
        "boty" to "shopping_clothes",
        "textil*" to "shopping_clothes",
        "moda" to "shopping_clothes",
        "fashion" to "shopping_clothes",
        "odziez*" to "shopping_clothes",
        "obuwie" to "shopping_clothes",
        "buty" to "shopping_clothes",
        "kleidung" to "shopping_clothes",
        "schuhe" to "shopping_clothes",
        "bekleidung" to "shopping_clothes",
        "clothes" to "shopping_clothes",
        "clothing" to "shopping_clothes",
        "shoes" to "shopping_clothes",
        "second hand" to "shopping_clothes",
        "secondhand" to "shopping_clothes",
        "sekac" to "shopping_clothes",
        "outlet" to "shopping_clothes",
        // --- Elektronika ---
        "elektro*" to "shopping_electronics",
        "electro*" to "shopping_electronics",
        "elektronik*" to "shopping_electronics",
        "computer*" to "shopping_electronics",
        "pocitac*" to "shopping_electronics",
        "komputer*" to "shopping_electronics",
        "notebook*" to "shopping_electronics",
        // --- Domácnost, zahrada ---
        "nabytek" to "housing_home",
        "nabytk*" to "housing_home",
        "domaci potreby" to "housing_home",
        "mebl*" to "housing_home",
        "mobel*" to "housing_home",
        "furnitur*" to "housing_home",
        "bytov*" to "housing_home",
        "domacnost*" to "housing_home",
        "zahrad*" to "housing_home",
        "ogrod*" to "housing_home",
        "garten*" to "housing_home",
        "garden*" to "housing_home",
        "hobbymarket" to "housing_home",
        "stavebnin*" to "housing_home",
        "baumarkt" to "housing_home",
        "zeleznarstv*" to "housing_home",
        "zelezarstv*" to "housing_home",
        "barvy laky" to "housing_home",
        "svitidl*" to "housing_home",
        "koberc*" to "housing_home",
        "matrac*" to "housing_home",
        "dekor*" to "housing_home",
        "bydleni" to "housing_home",
        "interier*" to "housing_home",
        // --- Děti ---
        "hrack*" to "shopping_other",
        "hracek" to "shopping_other",
        "zabawk*" to "shopping_other",
        "spielzeug*" to "shopping_other",
        "toys" to "shopping_other",
        "detsk*" to "shopping_other",
        "dzieci*" to "shopping_other",
        "kinder*" to "shopping_other",
        "baby" to "shopping_other",
        "kojeneck*" to "shopping_other",
        "skolka" to "shopping_other",
        "materska skola" to "shopping_other",
        "jesle" to "shopping_other",
        "krouzek" to "shopping_other",
        "krouzk*" to "shopping_other",
        // --- Mazlíčci ---
        "zverimex" to "shopping_other",
        "chovatel*" to "shopping_other",
        "krmiv*" to "shopping_other",
        "veterin*" to "shopping_other",
        "weterynar*" to "shopping_other",
        "tierarzt" to "shopping_other",
        "zoohandlung" to "shopping_other",
        "petshop" to "shopping_other",
        "pet shop" to "shopping_other",
        "granule" to "shopping_other",
        // --- Drogerie, zdraví a krása ---
        "drogeri*" to "shopping_drugstore",
        "drugstore" to "shopping_drugstore",
        "parfum*" to "shopping_drugstore",
        "parfem*" to "shopping_drugstore",
        "perfum*" to "shopping_drugstore",
        "kosmetik*" to "shopping_drugstore",
        "kosmetyk*" to "shopping_drugstore",
        "vitamin*" to "shopping_drugstore",
        "doplnky stravy" to "shopping_drugstore",
        // --- Klenoty, hodinky ---
        "klenot*" to "shopping_other",
        "zlatnic*" to "shopping_other",
        "sperk*" to "shopping_other",
        "jubiler*" to "shopping_other",
        "bizuter*" to "shopping_other",
        "schmuck" to "shopping_other",
        "jewel*" to "shopping_other",
        "hodinar*" to "shopping_other",
        "hodinky" to "shopping_other",
        "zegark*" to "shopping_other",
        "uhren" to "shopping_other",
        // --- Kancelář, nářadí ---
        "papirnic*" to "shopping_other",
        "papir*" to "shopping_other",
        "kancelar*" to "shopping_other",
        "naradi" to "shopping_other",
        "narad*" to "shopping_other",
        "tiskarn*" to "shopping_other",
        "kopirov*" to "shopping_other",
        "copy*" to "shopping_other",
        // --- Dárky, květiny ---
        "darek" to "charity",
        "darky" to "charity",
        "darkov*" to "charity",
        "gift*" to "charity",
        "suvenyr*" to "charity",
        "pamiat*" to "charity",
        "suvenir*" to "charity",
        "souvenir*" to "charity",
        "upominki" to "charity",
        "geschenk*" to "charity",
        "kvetin*" to "charity",
        "kvetiny" to "charity",
        "kwiaciarn*" to "charity",
        "blumen*" to "charity",
        "florist*" to "charity",
        // --- Volný čas, obchodní centra, sázky ---
        "bazar" to "shopping_other",
        "obchodni centrum" to "shopping_other",
        "obchodni dum" to "shopping_other",
        "nakupni centrum" to "shopping_other",
        "galeria handlowa" to "shopping_other",
        "centrum handlowe" to "shopping_other",
        "shopping center" to "shopping_other",
        "shopping centre" to "shopping_other",
        "einkaufszentrum" to "shopping_other",
        "loteri*" to "shopping_other",
        "sazkov*" to "shopping_other",
        "kasino" to "shopping_other",
        "casino" to "shopping_other",
        "herna" to "shopping_other",
        // --- Bydlení ---
        "najemne" to "housing_rent_mortgage",
        "najem" to "housing_rent_mortgage",
        "pronajem" to "housing_rent_mortgage",
        "czynsz" to "housing_rent_mortgage",
        "miete" to "housing_rent_mortgage",
        "hypote*" to "housing_rent_mortgage",
        "hipote*" to "housing_rent_mortgage",
        "kredyt hipoteczny" to "housing_rent_mortgage",
        "elektrin*" to "housing_utilities",
        "elektrick*" to "housing_utilities",
        "energie" to "housing_utilities",
        "energi*" to "housing_utilities",
        "plyn*" to "housing_utilities",
        "gaz" to "housing_utilities",
        "voda" to "housing_utilities",
        "vodne" to "housing_utilities",
        "stocne" to "housing_utilities",
        "vodarn*" to "housing_utilities",
        "vodovod*" to "housing_utilities",
        "teplo" to "housing_utilities",
        "teplarn*" to "housing_utilities",
        "odpad*" to "housing_utilities",
        "komunal*" to "housing_utilities",
        "popelnic*" to "housing_utilities",
        "stadtwerke" to "housing_utilities",
        "prad" to "housing_utilities",
        "zaloha energie" to "housing_utilities",
        "zalohy energie" to "housing_utilities",
        "sprava domu" to "housing_utilities",
        "spravce domu" to "housing_utilities",
        "druzstv*" to "housing_utilities",
        "spolecenstvi" to "housing_utilities",
        "vyuctovani" to "housing_utilities",
        "oprav*" to "housing_home",
        "remont*" to "housing_home",
        "instalater*" to "housing_home",
        "elektrikar*" to "housing_home",
        "malir*" to "housing_home",
        "uklid*" to "housing_home",
        "sprzatanie" to "housing_home",
        "reinigung" to "housing_home",
        "handwerk*" to "housing_home",
        "klempir*" to "housing_home",
        "zednic*" to "housing_home",
        "stavebni prace" to "housing_home",
        "rekonstruk*" to "housing_home",
        "kominik*" to "housing_home",
        "revize" to "housing_home",
        "podlah*" to "housing_home",
        // --- Komunikace ---
        "mobil*" to "comm_phone_internet",
        "telefon*" to "comm_phone_internet",
        "tarif*" to "comm_phone_internet",
        "dobiti kreditu" to "comm_phone_internet",
        "dobit*" to "comm_phone_internet",
        "internet*" to "comm_phone_internet",
        "wifi" to "comm_phone_internet",
        "software*" to "comm_apps",
        "aplikac*" to "comm_apps",
        "app store" to "comm_apps",
        "play store" to "comm_apps",
        "licenc*" to "comm_apps",
        "game*" to "comm_apps",
        "hry" to "comm_apps",
        "posta" to "shopping_other",
        "post" to "shopping_other",
        "poczta*" to "shopping_other",
        "zasilk*" to "shopping_other",
        "balik*" to "shopping_other",
        "paczk*" to "shopping_other",
        "paket*" to "shopping_other",
        "kuryr*" to "shopping_other",
        "courier*" to "shopping_other",
        "kurier*" to "shopping_other",
        "dorucen*" to "shopping_other",
        "postovne" to "shopping_other",
        // --- Práce / podnikání ---
        "hosting*" to "work_tools",
        "domain*" to "work_tools",
        "domen*" to "work_tools",
        "vps" to "work_tools",
        "server*" to "work_tools",
        "cloud" to "work_tools",
        "saas" to "work_tools",
        "coworking" to "work_tools",
        // --- Finanční výdaje ---
        "dan z" to "financial_taxes",
        "dane" to "financial_taxes",
        "danov*" to "financial_taxes",
        "silnicni dan" to "financial_taxes",
        "podatek*" to "financial_taxes",
        "urzad skarbowy" to "financial_taxes",
        "steuer*" to "financial_taxes",
        "finanzamt" to "financial_taxes",
        "socialni" to "financial_taxes",
        "pojist*" to "financial_insurance",
        "ubezpiecz*" to "financial_insurance",
        "versicherung*" to "financial_insurance",
        "insurance" to "financial_insurance",
        "uver*" to "financial_loans",
        "vracim" to "financial_loans",
        "pujck*" to "financial_loans",
        "splatk*" to "financial_loans",
        "pozyczk*" to "financial_loans",
        "raty" to "financial_loans",
        "rata" to "financial_loans",
        "darlehen" to "financial_loans",
        "spotrebitelsk*" to "financial_loans",
        "pokut*" to "financial_fees",
        "mandat*" to "financial_fees",
        "penale" to "financial_fees",
        "bussgeld" to "financial_fees",
        "strafzettel" to "financial_fees",
        "poradenstv*" to "financial_fees",
        "poradce" to "financial_fees",
        "advokat*" to "financial_fees",
        "pravni*" to "financial_fees",
        "pravnik" to "financial_fees",
        "notar*" to "financial_fees",
        "kancelaria prawna" to "financial_fees",
        "rechtsanwalt" to "financial_fees",
        "ucetni*" to "financial_fees",
        "ksiegow*" to "financial_fees",
        "steuerberat*" to "financial_fees",
        "konzultac*" to "financial_fees",
        "consult*" to "financial_fees",
        "poplat*" to "financial_fees",
        "oplata" to "financial_fees",
        "oplaty" to "financial_fees",
        "gebuhr*" to "financial_fees",
        "fee" to "financial_fees",
        "fees" to "financial_fees",
        "spravni" to "financial_fees",
        "urad" to "financial_fees",
        "vyzivn*" to "financial_fees",
        "alimen*" to "financial_fees",
        "unterhalt" to "financial_fees",
        // --- Investice, spoření ---
        "investic*" to "investments",
        "invest*" to "investments",
        "vyporadani nakupu" to "investments",
        "vyporadani" to "investments",
        "fond*" to "investments",
        "etf" to "investments",
        "broker*" to "investments",
        "burz*" to "investments",
        "crypto*" to "investments",
        "krypto*" to "investments",
        "bitcoin" to "investments",
        "sporic*" to "investments",
        "sporen*" to "investments",
        "oszczedn*" to "investments",
        "nemovit*" to "investments",
        "nieruchom*" to "investments",
        "realit*" to "investments",
        "immobil*" to "investments",
        "autobazar*" to "investments",
        "autosalon*" to "investments",
        "numismat*" to "investments",
        "filateli*" to "investments",
        "starozitn*" to "investments",
        "antik*" to "investments",
        // --- Ostatní (drobnosti, které nikam nepatří) ---
        "toalet*" to "others",
        "verejne wc" to "others",
        // --- Výběr hotovosti ---
        "bankomat*" to "cash_withdrawal",
        "atm" to "cash_withdrawal",
        "geldautomat" to "cash_withdrawal",
        "vyber hotovosti" to "cash_withdrawal",
    )

    /** Příjmová slova (jen pro příchozí pohyby). */
    val income: List<Pair<String, String>> = listOf(
        "mzda" to "income_wage",
        "mzdy" to "income_wage",
        "plat" to "income_wage",
        "vyplata" to "income_wage",
        "wynagrodzenie" to "income_wage",
        "gehalt" to "income_wage",
        "lohn" to "income_wage",
        "salary" to "income_wage",
        "wage*" to "income_wage",
        "faktur*" to "income_wage",
        "invoice*" to "income_wage",
        "odmena" to "income_wage",
        "honorar*" to "income_wage",
        "dohoda" to "income_wage",
        "dpp" to "income_wage",
        "urok*" to "income_interest",
        "dividend*" to "income_interest",
        "odsetki" to "income_interest",
        "zinsen" to "income_interest",
        "interest" to "income_interest",
        "vynos*" to "income_interest",
        "prodej" to "income_other",
        "sprzedaz" to "income_other",
        "verkauf" to "income_other",
        "sale" to "income_other",
        "najemne" to "income_other",
        "najem" to "income_other",
        "pronajem" to "income_other",
        "prispev*" to "income_other",
        "dotace" to "income_other",
        "grant*" to "income_other",
        "davka" to "income_other",
        "davky" to "income_other",
        "rodicovsk*" to "income_other",
        "materska" to "income_other",
        "nemocensk*" to "income_other",
        "podpora" to "income_other",
        "duchod" to "income_other",
        "vyporadani prodeje" to "income_other",
        "vraceni" to "income_refunds",
        "vratka" to "income_refunds",
        "refund*" to "income_refunds",
        "zwrot" to "income_refunds",
        "ruckzahlung" to "income_refunds",
        "erstattung" to "income_refunds",
        "storno" to "income_refunds",
        "preplatek" to "income_refunds",
        "kredit" to "income_refunds",
        "reklamace" to "income_refunds",
        "dar" to "income_other",
        "darek" to "income_other",
        "vyhra" to "income_other",
        "loterie" to "income_other",
        "stravenk*" to "income_other",
        "benefit*" to "income_other",
        "vyzivn*" to "income_other",
        "alimen*" to "income_other",
        "pujcka" to "income_other",
        "splatka" to "income_other",
    )
}
