package cz.heller.core.categorize

/**
 * Ruční pravidla obchodník → kategorie s nejvyšší prioritou (přebíjejí značky z [BrandLexicon]
 * i obecná slova z [GenericLexicon]). Klíče jsou normalizované tokenové fráze, `*` = prefix
 * tokenu; porovnává se po celých tokenech (viz [Lexicon]). Sem patří CZ/PL/MNE obchodníci,
 * které NSI nezná, instituce (pojišťovny, úřady) a záměrná rozhodnutí (ČT poplatek = daně).
 */
object SeedRules {

    val expense: List<Pair<String, String>> = listOf(
        // --- Potraviny ---
        "albert" to "food_groceries",
        "zabka" to "food_groceries",
        "biedronka" to "food_groceries",
        "kaufland" to "food_groceries",
        "billa" to "food_groceries",
        "tesco" to "food_groceries",
        "lidl" to "food_groceries",
        "penny" to "food_groceries",
        "globus" to "food_groceries",
        "makro" to "food_groceries",
        "spar" to "food_groceries",
        "coop" to "food_groceries",
        "jednota" to "food_groceries",
        "hruska" to "food_groceries",
        "flop" to "food_groceries",
        "carrefour" to "food_groceries",
        "auchan" to "food_groceries",
        "stokrotka" to "food_groceries",
        "dino" to "food_groceries",
        "wtc company" to "food_groceries",
        "mega 4 kasa" to "food_groceries",
        "kantun" to "food_groceries",
        "idea kotor" to "food_groceries",
        "voli" to "food_groceries",
        "rohlik" to "food_groceries",
        "kosik" to "food_groceries",
        "pont" to "food_groceries",
        // --- Restaurace, fast-food ---
        "mcdonald*" to "food_dining",
        "mcd" to "food_dining",
        "kfc" to "food_dining",
        "pasibus" to "food_dining",
        "vietthai" to "food_dining",
        "gastro west" to "food_dining",
        "little bay" to "food_dining",
        "flying bistro" to "food_dining",
        "bezrucova chata" to "food_dining",
        "tramontana" to "food_dining",
        "stari grad" to "food_dining",
        "sailor cattaro" to "food_dining",
        "krstac" to "food_dining",
        "nevjesta" to "food_dining",
        "callett" to "food_dining",
        "hasib" to "food_dining",
        "foodmania" to "food_dining",
        "makalu" to "food_dining",
        "dvor" to "food_dining",
        "mango mama" to "food_dining",
        "dame jidlo" to "food_dining",
        "damejidlo" to "food_dining",
        "wolt" to "food_dining",
        "foodora" to "food_dining",
        "bolt food" to "food_dining",
        "uber eats" to "food_dining",
        "pyszne" to "food_dining",
        "glovo" to "food_dining",
        "burfi" to "food_dining",
        "eatmeat" to "food_dining",
        "los capolitos" to "food_dining",
        "bistruck" to "food_dining",
        "ugo" to "food_dining",
        "eskafe" to "food_dining",
        "delikomat" to "food_dining",
        "coca cola" to "food_dining",
        // --- Bar, kavárna ---
        "starbucks" to "food_dining",
        "sbx" to "food_dining",
        "cokafe" to "food_dining",
        "shothouse" to "food_dining",
        "grycan" to "food_dining",
        "aroma 1" to "food_dining",
        "the spot" to "food_dining",
        "small talks" to "food_dining",
        "radioklub" to "food_dining",
        "impact hub" to "food_dining",
        "karlinska holka" to "food_dining",
        "moje misto" to "food_dining",
        "krizovatka" to "food_dining",
        // --- Palivo ---
        "shell" to "transport_fuel",
        "orlen" to "transport_fuel",
        "omv" to "transport_fuel",
        "mol" to "transport_fuel",
        "benzina" to "transport_fuel",
        "eurooil" to "transport_fuel",
        "jugopetrol" to "transport_fuel",
        "circle k" to "transport_fuel",
        "tank ono" to "transport_fuel",
        "ono" to "transport_fuel",
        // --- Parkování ---
        "parkum" to "transport_car_other",
        "park ra" to "transport_car_other",
        "brzeczkowice" to "transport_car_other",
        "balice manual" to "transport_car_other",
        "ap 1234" to "transport_car_other",
        "mpla" to "transport_car_other",
        "sejf" to "transport_car_other",
        // --- Vozidlo: údržba / půjčovna ---
        "auto toman" to "transport_car_other",
        "autotoman*" to "transport_car_other",
        "edalnice" to "transport_car_other",
        "helkon" to "transport_car_other",
        "discovercars" to "transport_car_other",
        // --- Veřejná doprava ---
        "kodis" to "transport_public",
        "csad" to "transport_public",
        "dpp" to "transport_public",
        "dpmo" to "transport_public",
        "dpmb" to "transport_public",
        "dpo" to "transport_public",
        "urbancard" to "transport_public",
        "litacka" to "transport_public",
        "odiska" to "transport_public",
        "idsjmk" to "transport_public",
        "pid" to "transport_public",
        "odis" to "transport_public",
        "ids jmk" to "transport_public",
        "dolazni terminal" to "transport_public",
        // --- Dálková doprava ---
        "flix*" to "transport_public",
        "regiojet" to "transport_public",
        "cd cz" to "transport_public",
        "ceske drahy" to "transport_public",
        "koleo" to "transport_public",
        "leo express" to "transport_public",
        "student agency" to "transport_public",
        "studentagency*" to "transport_public",
        "arriva" to "transport_public",
        "pkp intercity" to "transport_public",
        "ryanair" to "transport_public",
        "wizz*" to "transport_public",
        "smartwings" to "transport_public",
        "easyjet" to "transport_public",
        "lufthansa" to "transport_public",
        "eurowings" to "transport_public",
        "austrian airlines" to "transport_public",
        "lot polish" to "transport_public",
        // --- Taxi ---
        "bolt" to "transport_taxi",
        "uber" to "transport_taxi",
        "liftago" to "transport_taxi",
        "freenow" to "transport_taxi",
        // --- Dovolená, hotely ---
        "booking" to "leisure_holidays",
        "booking com" to "leisure_holidays",
        "airbnb" to "leisure_holidays",
        "monte put" to "leisure_holidays",
        "soa budva" to "leisure_holidays",
        "invia" to "leisure_holidays",
        "cedok" to "leisure_holidays",
        "fischer" to "leisure_holidays",
        // --- Telefon ---
        "t mobile" to "comm_phone_internet",
        "vodafone" to "comm_phone_internet",
        "o2" to "comm_phone_internet",
        "kaktus" to "comm_phone_internet",
        // --- Software, aplikace (osobní) ---
        "apple com" to "comm_apps",
        "apple com bill" to "comm_apps",
        "itunes" to "comm_apps",
        "google play" to "comm_apps",
        "google chrome" to "comm_apps",
        "microsoft" to "comm_apps",
        "playstation" to "comm_apps",
        "steam" to "comm_apps",
        "steamgames" to "comm_apps",
        "nintendo" to "comm_apps",
        "xbox" to "comm_apps",
        "icloud" to "comm_apps",
        "higgsfield" to "comm_apps",
        "dropbox" to "comm_apps",
        "adobe" to "comm_apps",
        // --- Práce / Podnikání (dev/AI nástroje) ---
        "anthropic" to "work_tools",
        "claude" to "work_tools",
        "openai" to "work_tools",
        "chatgpt" to "work_tools",
        "vercel" to "work_tools",
        "supabase" to "work_tools",
        "firecrawl" to "work_tools",
        "github" to "work_tools",
        "google cloud" to "work_tools",
        "google" to "work_tools",
        "idoklad" to "work_tools",
        "fakturoid" to "work_tools",
        "cloudflare" to "work_tools",
        "openrouter" to "work_tools",
        "entyai" to "work_tools",
        "wedos" to "work_tools",
        "forpsi" to "work_tools",
        "hetzner" to "work_tools",
        "digitalocean" to "work_tools",
        "aws" to "work_tools",
        "amazon web services" to "work_tools",
        "railway" to "work_tools",
        "netlify" to "work_tools",
        "jetbrains" to "work_tools",
        "notion" to "work_tools",
        "slack" to "work_tools",
        "zoom" to "work_tools",
        "figma" to "work_tools",
        "obsidian" to "work_tools",
        "elevenlabs" to "work_tools",
        "artlist" to "work_tools",
        "proton" to "work_tools",
        "zeptejse" to "work_tools",
        "autosell" to "work_tools",
        // --- Televize, streaming ---
        "netflix" to "comm_apps",
        "spotify" to "comm_apps",
        "hbo" to "comm_apps",
        "hbo max" to "comm_apps",
        "disney" to "comm_apps",
        "disney plus" to "comm_apps",
        "voyo" to "comm_apps",
        "canal" to "comm_apps",
        "skylink" to "comm_apps",
        "youtube" to "comm_apps",
        "youtube premium" to "comm_apps",
        "apple tv" to "comm_apps",
        "prime video" to "comm_apps",
        "o2 tv" to "comm_apps",
        "oneplay" to "comm_apps",
        // ČT/ČRo poplatek je povinný → Daně (na přání uživatele, ne „Televize").
        "ceska televize" to "financial_taxes",
        "vypalne ceska" to "financial_taxes",
        "cesky rozhlas" to "financial_taxes",
        // --- Elektronika ---
        "alza" to "shopping_electronics",
        "planeo" to "shopping_electronics",
        "datart" to "shopping_electronics",
        "mironet" to "shopping_electronics",
        "czc" to "shopping_electronics",
        "mall cz" to "shopping_electronics",
        "media markt" to "shopping_electronics",
        "mediamarkt" to "shopping_electronics",
        "electro world" to "shopping_electronics",
        "electroworld" to "shopping_electronics",
        "megapixel" to "shopping_electronics",
        "mudita" to "shopping_electronics",
        // --- Domácnost, zahrada ---
        "ikea" to "housing_home",
        "obi" to "housing_home",
        "hornbach" to "housing_home",
        "bauhaus" to "housing_home",
        "jysk" to "housing_home",
        "mountfield" to "housing_home",
        "castorama" to "housing_home",
        "leroy merlin" to "housing_home",
        "uni hobby" to "housing_home",
        "sconto" to "housing_home",
        "mobelix" to "housing_home",
        "xxxlutz" to "housing_home",
        "kika" to "housing_home",
        "asko" to "housing_home",
        "pepco" to "housing_home",
        "action" to "housing_home",
        "tedi" to "housing_home",
        // --- Oděvy a obuv ---
        "tk maxx" to "shopping_clothes",
        "zara" to "shopping_clothes",
        "deichmann" to "shopping_clothes",
        "reserved" to "shopping_clothes",
        "sinsay" to "shopping_clothes",
        "primark" to "shopping_clothes",
        "zalando" to "shopping_clothes",
        "h m" to "shopping_clothes",
        "c a" to "shopping_clothes",
        "medicine" to "shopping_clothes", // polská oděvní značka, ne lékárna
        "cropp" to "shopping_clothes",
        "house" to "shopping_clothes",
        "mohito" to "shopping_clothes",
        "ccc" to "shopping_clothes",
        "about you" to "shopping_clothes",
        "answear" to "shopping_clothes",
        "footshop" to "shopping_clothes",
        "vinted" to "shopping_clothes",
        // --- Sport, fitness ---
        "decathlon" to "health_sport",
        "form factory" to "health_sport",
        "sportisimo" to "health_sport",
        "multisport" to "health_sport",
        "hervis" to "health_sport",
        "intersport" to "health_sport",
        // --- Drogerie ---
        "rossmann" to "shopping_drugstore",
        "dm" to "shopping_drugstore",
        "dm drogerie" to "shopping_drugstore",
        "teta" to "shopping_drugstore",
        "notino" to "shopping_drugstore",
        "brainmarket" to "shopping_drugstore",
        // --- Zdravotní péče, lékárna ---
        "benu" to "health_care",
        "dr max" to "health_care",
        "drmax" to "health_care",
        "pilulka" to "health_care",
        // --- Pojištění (typy dříve než obecné) ---
        "auto pojisteni" to "transport_car_insurance",
        "povinne ruceni" to "transport_car_insurance",
        "havarijni" to "transport_car_insurance",
        "pojisteni vozidla" to "transport_car_insurance",
        "pojisteni domacnosti" to "financial_insurance",
        "pojisteni nemovitosti" to "financial_insurance",
        "pojisteni majetku" to "financial_insurance",
        "zivotni pojisteni" to "financial_insurance",
        "kooperativa" to "financial_insurance",
        "generali" to "financial_insurance",
        "allianz" to "financial_insurance",
        "uniqa" to "financial_insurance",
        "csob pojistovna" to "financial_insurance",
        "direct pojistovna" to "financial_insurance",
        "koop cz" to "financial_insurance",
        "koop" to "financial_insurance",
        "pbox" to "shopping_other",
        // --- Energie, komunál ---
        "cez" to "housing_utilities",
        "cez prodej" to "housing_utilities",
        "e on" to "housing_utilities",
        "eon" to "housing_utilities",
        "innogy" to "housing_utilities",
        "pre" to "housing_utilities",
        "prazska energetika" to "housing_utilities",
        "prazska plynarenska" to "housing_utilities",
        "centropol" to "housing_utilities",
        "bohemia energy" to "housing_utilities",
        "mnd" to "housing_utilities",
        "platba ele" to "housing_utilities",
        "tauron" to "housing_utilities",
        "pge" to "housing_utilities",
        "energa" to "housing_utilities",
        // --- Bydlení, služby ---
        "byt sluzby" to "housing_utilities",
        "spolecenstvi vlastniku" to "housing_utilities",
        "svj" to "housing_utilities",
        "bytove druzstvo" to "housing_utilities",
        "nedoplatek vyuctovani" to "housing_utilities",
        "fond oprav" to "housing_utilities",
        // --- Hypotéka ---
        "splatka hu" to "housing_rent_mortgage",
        "hyposporici" to "housing_rent_mortgage",
        // --- Půjčky, splátky ---
        "zonky" to "financial_loans",
        "cetelem" to "financial_loans",
        "home credit" to "financial_loans",
        "cofidis" to "financial_loans",
        "provident" to "financial_loans",
        "essox" to "financial_loans",
        "twisto" to "financial_loans",
        // --- Pokuty ---
        "usekove mereni" to "financial_fees",
        // --- Výběr hotovosti z bankomatu ---
        "bankomat" to "cash_withdrawal",
        "atm" to "cash_withdrawal",
        // --- Poplatky / úřady ---
        "magistrat" to "financial_fees",
        "mmhs" to "financial_fees",
        // --- Charita, dary ---
        "darujme" to "charity",
        "clovek v tisni" to "charity",
        "dar esk" to "charity",
        "splozene dite" to "charity",
        "adra" to "charity",
        "unicef" to "charity",
        "cerveny kriz" to "charity",
        "dobry andel" to "charity",
        "lekari bez hranic" to "charity",
        "ochrana svobody projevu" to "charity",
        // --- Investice ---
        "trading 212" to "investments",
        "trading212" to "investments",
        "frostember" to "investments",
        "portu" to "investments",
        "fondee" to "investments",
        "degiro" to "investments",
        "etoro" to "investments",
        "xtb" to "investments",
        "coinbase" to "investments",
        "binance" to "investments",
        "revolut" to "investments",
        "interactive brokers" to "investments",
        "penzijni" to "investments",
        "stavebni sporeni" to "investments",
        // --- Kultura, vstupenky ---
        "smsticket" to "leisure_culture",
        "goout" to "leisure_culture",
        "ticketmaster" to "leisure_culture",
        "ticketportal" to "leisure_culture",
        "cinestar" to "leisure_culture",
        "cinema city" to "leisure_culture",
        "mauzolej" to "leisure_culture",
        "bumbum comedy" to "leisure_culture",
        // --- Dárky, suvenýry ---
        "pamia" to "charity",
        // --- Obchodní centra / tržiště (volný čas) ---
        "futurum" to "shopping_other",
        "avion" to "shopping_other",
        "temu" to "shopping_other",
        "allegro" to "shopping_other",
        "aliexpress" to "shopping_other",
        "amazon" to "shopping_other",
        "ebay" to "shopping_other",
        "sazka" to "shopping_other",
        "tipsport" to "shopping_other",
        "fortuna" to "shopping_other",
        // --- Zdravotní a sociální pojištění, daně → Daně (povinné odvody) ---
        "zdravotni pojist*" to "financial_taxes",
        "revirni bratrska" to "financial_taxes",
        "socialniho zabezpeceni" to "financial_taxes",
        "socialni zabezpeceni" to "financial_taxes",
        "socialni pojisteni" to "financial_taxes",
        "socialni osvc" to "financial_taxes",
        "zdravotni osvc" to "financial_taxes",
        "financni urad" to "financial_taxes",
        "zalohy fu" to "financial_taxes",
        "rbp" to "financial_taxes",
        "vzp" to "financial_taxes",
        "vozp" to "financial_taxes",
        "ozp" to "financial_taxes",
        "cpzp" to "financial_taxes",
        "zpmv" to "financial_taxes",
        "ossz" to "financial_taxes",
        "cssz" to "financial_taxes",
        "pssz" to "financial_taxes",
        "mssz" to "financial_taxes",
        // --- Poštovní služby ---
        "zasilkovna" to "shopping_other",
        "packeta" to "shopping_other",
        "alzabox" to "shopping_other",
        "ceska posta" to "shopping_other",
        "ppl" to "shopping_other",
        "dpd" to "shopping_other",
        "gls" to "shopping_other",
        "dhl" to "shopping_other",
        "balikovna" to "shopping_other",
        "inpost" to "shopping_other",
        // --- Knihy, audio, předplatné ---
        "audible" to "leisure_culture",
        "kindle" to "leisure_culture",
        "audiolibrix" to "leisure_culture",
        "palmknihy" to "leisure_culture",
        "knihy dobrovsky" to "leisure_culture",
        "luxor" to "leisure_culture",
        "kosmas" to "leisure_culture",
        "martinus" to "leisure_culture",
        "empik" to "leisure_culture",
        "seznam premium" to "leisure_culture",
        // --- Vzdělávání ---
        "udemy" to "leisure_education",
        "coursera" to "leisure_education",
        "duolingo" to "leisure_education",
        "skillshare" to "leisure_education",
        // --- Internet ---
        "upc" to "comm_phone_internet",
        "starlink" to "comm_phone_internet",
        "netbox" to "comm_phone_internet",
        "poda" to "comm_phone_internet",
        // --- Mazlíčci ---
        "zverimex" to "shopping_other",
        "super zoo" to "shopping_other",
        "superzoo" to "shopping_other",
        "pet center" to "shopping_other",
        // --- Wellness ---
        "kosmeticky salon" to "health_sport",
        "kadernicky salon" to "health_sport",
        "frizer" to "health_sport",
        // --- Děti ---
        "dracik" to "shopping_other",
        "bambule" to "shopping_other",
        "smyk" to "shopping_other",
        // --- Vozidlo: leasing ---
        "leasing" to "transport_car_other",
    )

    /** Příjmová pravidla (jen když je pohyb příchozí). */
    val income: List<Pair<String, String>> = listOf(
        "sodexo" to "income_other",
        "edenred" to "income_other",
        "pluxee" to "income_other",
        "urad prace" to "income_other",
        "uradu prace" to "income_other",
        "ossz" to "income_other",
        "cssz" to "income_other",
        "pssz" to "income_other",
        "mssz" to "income_other",
        "financni urad" to "income_refunds",
        "vinted" to "income_other",
        "bazos" to "income_other",
        "aukro" to "income_other",
        "sbazar" to "income_other",
    )
}
